server:
  port: 8087

#spring:
#  application:
#      name: ProductService
#  data:
#   mongodb:
#    database: DealsCoupenFinderApp
#    host: localhost
#    port: 27017

spring:
  data:
    mongodb:
      uri: mongodb+srv://#######:*****@cluster0.8qbu7b0.mongodb.net/productsdata?retryWrites=true&w=majority
    
data:
  exception:
     msg: Record Already Exists..!!
     nameNotFound: Record name Not Found..!!
     dataNotFound: Record name Not Found..!!
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt
jwt:
  secret: secrectkey123       
    
